name: "tagged-release"

on:
  workflow_dispatch:

#on:
  #push:
    #tags:
      #- "v*"

permissions:
  contents: write

jobs:
  release-build:
    name: "Release Build"
    runs-on: ubuntu-latest
    steps:
    - run: gh release create ${{github.ref_name}} Strangevania.zip
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
